# Generated by Django 4.2.8 on 2023-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="average_response_time",
            field=models.DurationField(default=0),
        ),
    ]
