# Generated by Django 4.2.8 on 2023-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0002_alter_historicalperformance_average_response_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="average_response_time",
            field=models.DurationField(),
        ),
    ]
