# Generated by Django 4.2.8 on 2023-12-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_alter_historicalperformance_average_response_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
