# Generated by Django 4.2.8 on 2023-12-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0004_alter_historicalperformance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="average_response_time",
            field=models.DurationField(null=True),
        ),
    ]
